### PR TITLE
Remove Stephen Colbert from exclude list

### PR DESCRIPTION
**Pull request by rnreekez**

### CODE REVIEW

**Comment by sander1** [comment]
It's there for a good reason, it doesn't work with the current CBS channel code...

**Comment by rnreekez** [comment]
The API endpoints were updated last night w/ the premier. I deployed this version on my local instance and did not run into issues streaming the first episode. Is there a preferred way to validate support beyond my local instance?

**Comment by sander1** [comment]
Let me check that out, maybe they changed something now that the show is really on tv.

**Comment by sander1** [comment]
Tested and working, cool!! Thanks!

**Pull request merged**
